const constants = {
    LOCAL_STORAGE_KEY_STATION : "station",
    LOCAL_STORAGE_KEY_ALLLINE : "allLine",
    LOCAL_STORAGE_KEY_LINE2 : "2호선",
    LOCAL_STORAGE_KEY_LINE3 : "3호선",
    LOCAL_STORAGE_KEY_LINENEW : "신분당선",
    LOCAL_STORAGE_KEY_SECTION : "sectionInfo",
    TABLE_TARGET : "tr",
    FIND_PATH_STANDARD_DISTANCE : "distance",
    FIND_PATH_STANDARD_DURATION : "duration",
    STATION_VALUE_CHILDNODE_INDEX : 0,
    LINE_VALUE_CHILDNODE_INDEX : 0,
    SECTION_VALUE_CHILDNODE_INDEX : 1,
    STATION_NAME_MINIMUM_LENGTH : 2,
    MINIMUM_NUMBER_OF_SECTION : 2,
    MANAGER_BUTTON_STRING_LENGTH : 7,
    SECTION_ADD_DEFAULT_DISTANCE : 2,
    SECTION_ADD_DEFAULT_DURATION : 3,
    SECTION_ADD_END_POINT_DISTANCE : 0,
    SECTION_ADD_END_POINT_DURATION : 0,
    FIRST_STATION_INDEX : 0,
    LAST_STATION_INDEX : 1,
    LINE_NAME_FORMAT : "선"
};

export {constants};