const constants = {
    LOCAL_STORAGE_KEY_STATION : "station",
    LOCAL_STORAGE_KEY_ALLLINE : "allLine",
    LOCAL_STORAGE_KEY_LINE2 : "2호선",
    LOCAL_STORAGE_KEY_LINE3 : "3호선",
    LOCAL_STORAGE_KEY_LINENEW : "신분당선",
    TABLE_TARGET : "tr",
    STATION_VALUE_CHILDNODE_INDEX : 0,
    LINE_VALUE_CHILDNODE_INDEX : 0,
    STATION_NAME_MINIMUM_LENGTH : 2,
    LINE_NAME_FORMAT : "선"
};

export {constants};